//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlipTech_FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollement
    {
        public string t_id { get; set; }
        public string c_id { get; set; }
        public string s_id { get; set; }
        public string semester { get; set; }
        public string grade { get; set; }
        public int e_id { get; set; }
    }
}
