//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlipTech_FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public string s_id { get; set; }
        public string time { get; set; }
        public string v_id { get; set; }
        public string session { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public int h_id { get; set; }
    }
}
