//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlipTech_FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson_Plan
    {
        public string c_id { get; set; }
        public string less_id { get; set; }
        public string week { get; set; }
    }
}
