//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlipTech_FYP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Demo_Data_EnteredEntities : DbContext
    {
        public Demo_Data_EnteredEntities()
            : base("name=Demo_Data_EnteredEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Enrollement> Enrollements { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<Lesson_Plan> Lesson_Plan { get; set; }
        public virtual DbSet<List_Topic> List_Topic { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<Presentation> Presentations { get; set; }
        public virtual DbSet<Rate> Rates { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<video_data> video_data { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
    }
}
