//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlipTech_FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public string s_id { get; set; }
        public string v_data_id { get; set; }
        public string notes { get; set; }
        public string session { get; set; }
        public int n_id { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual video_data video_data { get; set; }
    }
}
