//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlipTech_FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presentation
    {
        public string s_id { get; set; }
        public string topic_id { get; set; }
        public Nullable<System.DateTime> p_date { get; set; }
        public string session { get; set; }
        public string t_id { get; set; }
        public Nullable<double> marks { get; set; }
        public int p_id { get; set; }
    }
}
