//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlipTech_FYP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class video_data
    {
        public string v_data_id { get; set; }
        public string v_id { get; set; }
        public string topic_id { get; set; }
        public string start_time { get; set; }
        public string end_time { get; set; }
        public string key_word { get; set; }
        public string url { get; set; }
    }
}
